ignore:
  - "third_party/"  # ignore folders and all its contents

coverage:
  status:
    patch: no
    project:
      default: false
      tests:
        target: 90%
        paths: "tests/"
      app:  
        target: 90%
        paths: "!tests/"
