ignore:
  - "third_party/"  # ignore folders and all its contents

coverage:
  status:
<<<<<<< HEAD
=======
    patch: no
>>>>>>> system_tests/cli
    project:
      default: false
      tests:
        target: 100%
        paths: "tests/"
      app:  
        target: 90%
        paths: "!tests/"
<<<<<<< HEAD
=======

>>>>>>> system_tests/cli
