version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing gcc
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Installing wget
          command: 'apt-get update && apt-get install -y wget'
      - run:
          name: Download Premake5
          command: 'wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-linux.tar.gz'
      - run:
          name: Install Premake5
          command: 'tar -xvf premake-5.0.0-alpha13-linux.tar.gz'
      - run:
          name: Creating Build Files
          command: './premake5 gmake'
      - run:
          name: Build Debug
          command: 'make -C gmake -j 12 config=debug verbose=true'
      - run:
          name: Build Release
          command: 'make -C gmake -j 12 config=release verbose=true'
      - run:
          name: Run Debug Tests
          command: './bin/tests/debug_tests'
      - run:
          name: Run Release Tests
          command: './bin/tests/release_tests'
      - run:
          name: Upload code coverage
          command: 'bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect reports" '
