version: 2

jobs:
  build:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Download Premake5
          command: 'wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-linux.tar.gz'
      - run:
          name: Install Premake5
          command: 'tar -xvf premake-5.0.0-alpha13-linux.tar.gz'
      - run:
          name: Creating Build Files
          command: './premake5 gmake'
      - run:
          name: Build and run
          command: './build.sh'
      - run:
          name: Upload code coverage
          command: 'bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect reports" '

